services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            args:
                APP_ENV: 'local'
                HOST_UID: '${HOST_UID}'
                XDEBUG_ENABLE: '${XDEBUG_ENABLE:-false}'
        volumes:
            - ./.docker/s6-overlay/services.d:/etc/services.d
            - .:/var/www/html
        environment:
            APP_ENV: 'local'
            XDEBUG_ENABLE: '${XDEBUG_ENABLE:-false}'

    mysql:
        image: mysql:8
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysqldata:/var/lib/mysql

#    npm:
#        image: node:16.13-alpine3.14
#        user: node
#        volumes:
#            - ./:/assets
#        working_dir: /assets
#        entrypoint: ['npm', '--no-bin-links']

#    testdb:
#        image: mysql:8
#        tmpfs: /var/lib/mysql

volumes:
    mysqldata:
