services:
    app:
        build:
            context: .
            dockerfile: .docker/dev.Dockerfile
            args:
                HOST_UID: '${HOST_UID}'
                XDEBUG_ENABLE: '${XDEBUG_ENABLE:-false}'
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_ENABLE: '${XDEBUG_ENABLE:-false}'

    mysql:
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'

#    testdb:
#        image: mysql:8
#        tmpfs: /var/lib/mysql

    localtunnel:
        build:
            context: ./.docker/localtunnel
        command: "usr/local/bin/lt --port 80 --local-host app"
        depends_on:
            - app
